version: '3.9'

services:
  mongodb:
    image: mongo:4.0.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    restart: always

  api:
    build:
      context: .
    ports:
      - 5000:5000
    restart: always 
    depends_on:
      - mongodb 
    